	// the different languages.
	var mob_leng = { 
		'es' : {
				'info_username': 'Usuario:',
				'info_email': 'Correo:',
				'info_name': 'Nombre:',
				'info_lastname': 'Apellido:',
				'info_newpass': 'Nueva Contraseña:',
				'note_newpass': 'Rellena el campo <b>"Nueva Contraseña"</b> solo si cambiaras tu contraseña actual por una nueva. <b>Cambiar el correo</b> requerira el volver a activar la cuenta.',
				'save_btn': 'Guardar',
				'home_msg_2': 'Deseas exportar una segmentacion en formato JSON, XML, o otro formato? Ve <a href=""> aquí </a>',
				'h_login' : 'Inicio de Sesión',
				'login_msg_1': 'Inicia sesión para hacer uso de la herramienta de segmentación!.',
				'user_username' : 'Usuario',
				'user_pass' : 'Contraseña',
				'h_sign' : 'Registro',
				'logout_btn': 'Cerrar Sesión',
				'user_email2' : 'Correo',
				'user_username2' : 'Usuario',
				'user_pass2' : 'Contraseña',
				'p_terms' : 'Acepto los Términos y Condiciones',
				'h_home' : ' - PRINCIPAL - ',
				'startB' : 'COMENZAR',
				'h_rank' : ' - PUNTUACIONES - ',
				'rank_msg_1' : 'Tus puntuaciones y las puntuaciones globales de las segmentaciones realizadas de esta página web, basada en cada granularidad.',
				'rank_msg_2': 'Necesitas iniciar sesión para ver las puntuaciones.',
				'p_tip' : 'Pro Tip: el truco para obtener un buen puntaje es hacer una buena segmentación en poco tiempo.',
				'h_info' : ' - INFORMACIÓN - ',
				'infobtn': 'La <b> Información </b> es donde puedes observar el progreso de tu segmentación, posee los detalles de los bloques realizados, o los parámetros usados tales como la granularidad.',
				'addbtn': ' La acción de <b> Nuevo bloque </b>  es usada para crear nuevos bloques. Haz clic en el botón para activarlo y después haz clic sobre alguna sección de la página para crear un nuevo bloque.',		
				'deletebtn': 'La acción <b> Eliminar bloque </b> es usada para eliminar un bloque. Haz clic en el botón para activarlo y después haz clic en el bloque que deseas eliminar.',
				'mergebtn': 'La acción <b> Unir bloque </b> es usada para combinar dos bloques en uno. Haz clic en el botón para activarlo y después haz clic en los dos bloques que deseas combinar.',				
				'cutbtn': 'La acción <b> Cortar bloque </b> es usada para separar dos bloques que se solapan entre sí. Haz clic en el botón para activarlo, después haz clic sobre el bloque que deseas se preserve sobre el otro, finalmente haz clic sobre el segundo bloque (éste será cortado).',
				'tagbtn': 'La acción <b> Etiquetar bloque </b> es usada para agregar una etiqueta a un bloque. Haz click en el botón para activarlo, después haz clic sobre el bloque a etiquetar y elige una etiqueta de la lista.',
				'selectbtn': 'La acción <b> Seleccionar bloque </b> es usada para mostrar la información de un bloque. Haz clic en el botón para activarlo, después haz clic sobre algún bloque para observar su información.',
				'submitbtn': 'La acción <b> Enviar segmentación </b> es usada para enviar los datos de la segmentación realizada hacia el servidor. Haz click en el botón para enviar la segmentación, en caso de error un mensaje debería aparecer.',
				'p_credit' : 'Los iconos utilizados son cortesia de FontAwesome.',
				'recover_btn': 'RECOBRAR',
				'forgot_btn': 'Olvidaste tu Clave/Usuario?'
					},

		'en' : {
				'info_username': 'Username:',
				'info_email': 'Email:',
				'info_name': 'Name:',
				'info_lastname': 'Last Name:',
				'info_newpass': 'New Password:',
				'note_newpass': 'Fill the <b>"New Password"</b> field only if you want to change your current password. <b>Changing the email</b> will require a re-activation.',
				'save_btn': 'Save',
				'home_msg_2': 'Do you want to export the segmentation into JSON, XML or other format? go <a href=""> here </a>',
				'h_login' : 'Login',
				'login_msg_1': 'Log in to use the segmentation tool!.',
				'user_username' : 'Username',
				'user_pass' : 'Password',
				'h_sign' : 'Sign Up',
				'logout_btn': 'Log Out',
				'user_email2' : 'Email',
				'user_username2' : 'Username',
				'user_pass2' : 'Password',
				'p_terms' : 'I agreed with the Terms & Conditions',
				'h_home' : ' - HOME - ',
				'startB' : 'START',
				'h_rank' : ' - RANKING - ',
				'rank_msg_1' : 'Yours and global best scores of the segmentations of this web page, based on each granularity',
				'rank_msg_2': 'You need to be logged in to watch your score and the global scores.',
				'p_tip' : 'Pro Tip: the key to have a great score is to make a great segmentation in record time. ',
				'h_info' : ' - INFORMATION - ',
				'infobtn': 'The <b> Information </b> is where you can observe the progress of your segmentation, it has details of the blocks made, or the params used such as the granularity.',
				'addbtn': 'The <b> New block </b> action is used to create new blocks. Just click the button to activate it and click a section on the page to create the new block. You can guide yourself using the highlight guide.',		
				'deletebtn': 'The <b> Delete block </b> action is used to delete a block. Just click the button to activate it and click on the blocks you want to delete.',
				'mergebtn': 'The <b> Merge block </b> action is used to combine two blocks into one. Just click the button to activate it and then click the two blocks blocks you want to combine.',				
				'cutbtn': 'The <b> Cut block </b> action is used to separate two blocks that are overlapping eachother. Just click the button to activate it, then, click the block you want to "preservate" over the other and later, click the second block (this one will be cut).',
				'tagbtn': 'The <b> Tag block </b> action is used to add a tag to a block. Just click the button to activate it, then click the block you want to identify and choose from the list of tags.',
				'selectbtn': 'The <b> Select block </b> action is used to show a block\'s details. Just click the button to activate it, then click any block to show its details.',
				'submitbtn': 'The <b> Submit segmentation </b> action is used to send your segmentation details to the server. Just click the button to send the segmentation, if there\'s any error an alert should popup.',
				'p_credit' : 'The icons were courtesy of FontAwesome.',
				'recover_btn': 'RECOVER',
				'forgot_btn': 'Forgot Password/Username?'
					},

		'fr' : {

				'info_username': 'Usuario:',
				'info_email': 'Correo:',
				'info_name': 'Nombre:',
				'info_lastname': 'Apellido:',
				'info_newpass': 'Nueva Contraseña:',
				'note_newpass': 'Rellena el campo <b>"Nueva Contraseña"</b> solo si cambiaras tu contraseña actual por una nueva. <b>Cambiar el correo</b> requerira el volver a activar la cuenta.',
				'save_btn': 'Guardar',
				'home_msg_2': 'Deseas exportar una segmentacion en formato JSON, XML, o otro formato? Ve <a href=""> aquí </a>',
				'h_login' : 'Login',
				'login_msg_1': 'Inicia sesión para hacer uso de la herramienta de segmentación!.',
				'user_username' : 'Username',
				'user_pass' : 'Mot de passe',
				'p_session' : 'Ne pas finir la session.',
				'h_sign' : 'Entre',
				'logout_btn': 'Cerrar Sesión',
				'user_email2' : 'Email',
				'user_username2' : 'Login',
				'user_pass2' : 'Mote de passe',
				'p_terms' : 'Je suis d\'accord avec les termes et conditions',
				'h_home' : ' - ACCUEIL - ',
				'p_intro' : 'Si vous avais des questions, sur le fontionement de ce logiciel, regardez les videos tutorials, localizée dans la section de "Information".',
				'startB' : 'Démarrer',
				'h_rank' : ' - CLASSEMENT - ',
				'rank_msg_1' : 'Tus puntuaciones y las puntuaciones globales de las segmentaciones realizadas de esta página web, basada en cada granularidad.',
				'rank_msg_2': 'Necesitas iniciar sesión para ver las puntuaciones.',
				'p_tip' : 'Pro Tip: pour avoir un bon score fait la segmentation le plus vit possible ',
				'h_info' : ' - RENSEIGNEMENTS - ',
				'infobtn': 'La <b> Información </b> es donde puedes observar el progreso de tu segmentación, posee los detalles de los bloques realizados, o los parámetros usados tales como la granularidad.',
				'addbtn': ' La acción de <b> Nuevo bloque </b>  es usada para crear nuevos bloques. Haz clic en el botón para activarlo y después haz clic sobre alguna sección de la página para crear un nuevo bloque.',		
				'deletebtn': 'La acción <b> Eliminar bloque </b> es usada para eliminar un bloque. Haz clic en el botón para activarlo y después haz clic en el bloque que deseas eliminar.',
				'mergebtn': 'La acción <b> Unir bloque </b> es usada para combinar dos bloques en uno. Haz clic en el botón para activarlo y después haz clic en los dos bloques que deseas combinar.',				
				'cutbtn': 'La acción <b> Cortar bloque </b> es usada para separar dos bloques que se solapan entre sí. Haz clic en el botón para activarlo, después haz clic sobre el bloque que deseas se preserve sobre el otro, finalmente haz clic sobre el segundo bloque (éste será cortado).',
				'tagbtn': 'La acción <b> Etiquetar bloque </b> es usada para agregar una etiqueta a un bloque. Haz click en el botón para activarlo, después haz clic sobre el bloque a etiquetar y elige una etiqueta de la lista.',
				'selectbtn': 'La acción <b> Seleccionar bloque </b> es usada para mostrar la información de un bloque. Haz clic en el botón para activarlo, después haz clic sobre algún bloque para observar su información.',
				'submitbtn': 'La acción <b> Enviar segmentación </b> es usada para enviar los datos de la segmentación realizada hacia el servidor. Haz click en el botón para enviar la segmentación, en caso de error un mensaje debería aparecer.',
				'p_credit' : 'Les icons sont avec autorization du FontAwesome.',
				'recover_btn': 'RECOBRAR',
				'forgot_btn': 'Olvidaste tu Clave/Usuario?'
					}
	};
