	// the different languages.

	// For the popup
	var mob_leng = { 
		'es' : {
				'info_username': 'Usuario:',
				'info_email': 'Correo:',
				'info_name': 'Nombre:',
				'info_lastname': 'Apellido:',
				'info_newpass': 'Nueva Contraseña:',
				'note_newpass': 'Rellena el campo <b>"Nueva Contraseña"</b> solo si cambiaras tu contraseña actual por una nueva. <b>Cambiar el correo</b> requerira el volver a activar la cuenta.',
				'save_btn': 'Guardar',
				'home_msg_2': 'Recuerda revisar la sección de información (la gran I ), también, visita el Repositorio  MoB para observar tu segmentación <a href="https://mob.ciens.ucv.ve" target="_blank"> aqui </a>',
				'h_login' : 'Inicio de Sesión',
				'login_msg_1': 'Inicia sesión para hacer uso de la herramienta de segmentación!.',
				'user_username' : 'Usuario',
				'user_pass' : 'Contraseña',
				'h_sign' : 'Registro',
				'logout_btn': 'Cerrar Sesión',
				'user_email2' : 'Correo',
				'user_username2' : 'Usuario',
				'user_pass2' : 'Contraseña',
				'p_terms' : 'Acepto los Términos y Condiciones',
				'h_home' : ' - PRINCIPAL - ',
				'startB' : 'COMENZAR',
				'h_rank' : ' - PUNTUACIONES - ',
				'rank_msg_1' : 'Tus puntuaciones y las puntuaciones globales de las segmentaciones realizadas de esta página web, basada en cada granularidad.',
				'rank_msg_2': 'Necesitas iniciar sesión para ver las puntuaciones.',
				'p_tip' : 'Pro Tip: el truco para obtener un buen puntaje es hacer una buena segmentación en poco tiempo.',
				'h_info' : ' - INFORMACIÓN - ',
				'infobtn': 'La <b> Información </b> es donde puedes observar el progreso de tu segmentación, posee los detalles de los bloques realizados, o los parámetros usados tales como la granularidad.',
				'addbtn': ' La acción de <b> Nuevo bloque </b>  es usada para crear nuevos bloques. Haz clic en el botón para activarlo y después haz clic sobre alguna sección de la página para crear un nuevo bloque.',		
				'deletebtn': 'La acción <b> Eliminar bloque </b> es usada para eliminar un bloque. Haz clic en el botón para activarlo y después haz clic en el bloque que deseas eliminar.',
				'mergebtn': 'La acción <b> Unir bloque </b> es usada para combinar dos bloques en uno. Haz clic en el botón para activarlo y después haz clic en los dos bloques que deseas combinar.',				
				'cutbtn': 'La acción <b> Cortar bloque </b> es usada para separar dos bloques que se solapan entre sí. Haz clic en el botón para activarlo, después haz clic sobre el bloque que deseas se preserve sobre el otro, finalmente haz clic sobre el segundo bloque (éste será cortado).',
				'tagbtn': 'La acción <b> Etiquetar bloque </b> es usada para agregar una etiqueta a un bloque. Haz click en el botón para activarlo, después haz clic sobre el bloque a etiquetar y elige una etiqueta de la lista.',
				'selectbtn': 'La acción <b> Seleccionar bloque </b> es usada para mostrar la información de un bloque. Haz clic en el botón para activarlo, después haz clic sobre algún bloque para observar su información.',
				'submitbtn': 'La acción <b> Enviar segmentación </b> es usada para enviar los datos de la segmentación realizada hacia el servidor. Haz click en el botón para enviar la segmentación, en caso de error un mensaje debería aparecer.',
				'p_credit' : 'Los iconos utilizados son cortesia de FontAwesome.',
				'recover_btn': 'RECOBRAR',
				'forgot_btn': 'Olvidaste tu Clave/Usuario?'
					},

		'en' : {
				'info_username': 'Username:',
				'info_email': 'Email:',
				'info_name': 'Name:',
				'info_lastname': 'Last Name:',
				'info_newpass': 'New Password:',
				'note_newpass': 'Fill the <b>"New Password"</b> field only if you want to change your current password. <b>Changing the email</b> will require a re-activation.',
				'save_btn': 'Save',
				'home_msg_2': 'Remember to check the info section (the big I), also, visit the MoB Repository To watch your segmentation <a href="https://mob.ciens.ucv.ve" target="_blank"> here </a>',
				'h_login' : 'Login',
				'login_msg_1': 'Log in to use the segmentation tool!.',
				'user_username' : 'Username',
				'user_pass' : 'Password',
				'h_sign' : 'Sign Up',
				'logout_btn': 'Log Out',
				'user_email2' : 'Email',
				'user_username2' : 'Username',
				'user_pass2' : 'Password',
				'p_terms' : 'I agreed with the Terms & Conditions',
				'h_home' : ' - HOME - ',
				'startB' : 'START',
				'h_rank' : ' - RANKING - ',
				'rank_msg_1' : 'Yours and global best scores of the segmentations of this web page, based on each granularity',
				'rank_msg_2': 'You need to be logged in to watch your score and the global scores.',
				'p_tip' : 'Pro Tip: the key to have a great score is to make a great segmentation in record time. ',
				'h_info' : ' - INFORMATION - ',
				'infobtn': 'The <b> Information </b> is where you can observe the progress of your segmentation, it has details of the blocks made, or the params used such as the granularity.',
				'addbtn': 'The <b> New block </b> action is used to create new blocks. Just click the button to activate it and click a section on the page to create the new block. You can guide yourself using the highlight guide.',		
				'deletebtn': 'The <b> Delete block </b> action is used to delete a block. Just click the button to activate it and click on the blocks you want to delete.',
				'mergebtn': 'The <b> Merge block </b> action is used to combine two blocks into one. Just click the button to activate it and then click the two blocks blocks you want to combine.',				
				'cutbtn': 'The <b> Cut block </b> action is used to separate two blocks that are overlapping eachother. Just click the button to activate it, then, click the block you want to "preservate" over the other and later, click the second block (this one will be cut).',
				'tagbtn': 'The <b> Tag block </b> action is used to add a tag to a block. Just click the button to activate it, then click the block you want to identify and choose from the list of tags.',
				'selectbtn': 'The <b> Select block </b> action is used to show a block\'s details. Just click the button to activate it, then click any block to show its details.',
				'submitbtn': 'The <b> Submit segmentation </b> action is used to send your segmentation details to the server. Just click the button to send the segmentation, if there\'s any error an alert should popup.',
				'p_credit' : 'The icons were courtesy of FontAwesome.',
				'recover_btn': 'RECOVER',
				'forgot_btn': 'Forgot Password/Username?'
					},

		'fr' : {

				'info_username': 'Utilisateur:',
				'info_email': 'Mail:',
				'info_name': 'Nom:',
				'info_lastname': 'Le nom:',
				'info_newpass': 'Nouveau mot de passe:',
				'note_newpass': 'Remplissez le champ <b> "Nouveau mot de passe" </ b> uniquement si vous changez votre mot de passe actuel en un nouveau. <b> Modifier le mail </ b> nécessitera de réactiver le compte.',
				'save_btn': 'sauvegarder',
				'home_msg_2': 'N\'oubliez pas de vérifier la section d\'information (le grand I), aussi, visitez le référentiel MoB pour observer votre segmentation <a href="https://mob.ciens.ucv.ve" target="_blank"> ici </a>',
				'h_login' : 'Login',
				'login_msg_1': 'Connectez-vous pour utiliser l\'outil de segmentation!',
				'user_username' : 'Username',
				'user_pass' : 'Mot de passe',
				'p_session' : 'Ne pas finir la session.',
				'h_sign' : 'Entre',
				'logout_btn': 'Fermer la session',
				'user_email2' : 'Email',
				'user_username2' : 'Login',
				'user_pass2' : 'Mote de passe',
				'p_terms' : 'Je suis d\'accord avec les termes et conditions',
				'h_home' : ' - ACCUEIL - ',
				'p_intro' : 'Si vous avais des questions, sur le fontionement de ce logiciel, regardez les videos tutorials, localizée dans la section de "Information".',
				'startB' : 'Démarrer',
				'h_rank' : ' - CLASSEMENT - ',
				'rank_msg_1' : 'Vos scores et les scores globaux des segmentations faites à partir de cette page web, en fonction de chaque granularité.',
				'rank_msg_2': 'Vous devez vous connecter pour voir les scores.',
				'p_tip' : 'Pro Tip: pour avoir un bon score fait la segmentation le plus vit possible ',
				'h_info' : ' - RENSEIGNEMENTS - ',
				'infobtn': 'Le <b> Information </b> est l\'endroit où vous pouvez observer la progression de votre segmentation, avoir les détails des blocs faits, ou les paramètres utilisés tels que la granularité.',
				'addbtn': ' L\'action de <b> Nouveau bloc </b> est utilisée pour créer de nouveaux blocs. Cliquez sur le bouton pour l\'activer puis cliquez sur une section de la page pour créer un nouveau bloc.',		
				'deletebtn': 'L\'action <b> Supprimer bloc </b> permet de supprimer un bloc. Cliquez sur le bouton pour l\'activer puis cliquez sur le bloc que vous souhaitez supprimer.',
				'mergebtn': 'L\'action <b> Rejoindre le bloc </b> permet de combiner deux blocs en un seul. Cliquez sur le bouton pour l\'activer puis cliquez sur les deux blocs que vous souhaitez combiner.',				
				'cutbtn': 'L\'action <b> Couper bloc </ b> est utilisée pour séparer deux blocs qui se chevauchent. Cliquez sur le bouton pour l\'activer, puis cliquez sur le bloc que vous voulez conserver par dessus l\'autre, enfin cliquez sur le second bloc (il sera coupé).',
				'tagbtn': 'L\'action <b> Bloc d\'étiquette </b> est utilisée pour ajouter une étiquette à un bloc. Cliquez sur le bouton pour l\'activer, puis cliquez sur le bloc pour marquer et choisissez une étiquette dans la liste.',
				'selectbtn': 'L\'action <b> Sélectionner bloc </b> permet d\'afficher les informations d\'un bloc. Cliquez sur le bouton pour l\'activer, puis cliquez sur un bloc pour observer ses informations.',
				'submitbtn': 'L\'action <b> Envoyer la segmentation </b> permet d\'envoyer les données de segmentation au serveur. Cliquez sur le bouton pour envoyer la segmentation, en cas d\'erreur un message devrait apparaître.',
				'p_credit' : 'Les icons sont avec autorization du FontAwesome.',
				'recover_btn': 'Récupérer',
				'forgot_btn': 'oublié passe/username?'
					}
	};


// for the script/ tool
var mob_leng_s = {

	'es': {
		'a_info':'Información',
		'a_insert':'Insertar nuevo bloque',
		'a_delete':'Eliminar bloque',
		'a_merge':'Unir bloques',
		'a_cut':'Cortar bloques',
		'a_tag':'Editar etiqueta',
		'a_select':'Seleccionar bloque',
		'a_submit':'Enviar segmentación',
		'i_legend': ' <b class="MoB-span"> Leyenda </b> </br><span style="color:rgb(90, 194, 236);" class="MoB-span"> <b class="MoB-span"> Aceptable </b> </span> = El bloque esta bien. </br><span style="color:rgb(255, 193, 7); " class="MoB-span"> <b class="MoB-span"> Alerta </b> </span> = La granularidad del bloque está muy por encima de la escogida. </br><span style="color:rgb(169, 68, 66);" class="MoB-span"> <b class="MoB-span"> Error </b> </span> = La granularidad del bloque no es aceptada, el bloque está intersectando con otro o le falta la etiqueta.',
		'i_nblock':'#Bloques: ',
		'i_blockta':'Total área de bloques: ',
		'i_gran':'Granularidad: ',
		'i_editg':'editar',
		'i_div':'Dividido en: ',
		'i_div2':' partes',
		'i_blockma':'Área mínima para bloques: ',
		'i_totalma':'Área mínima total: ',
		'm_message':'Mensaje MoB',
		'm_cancel':'Cancelar',
		'm_select':'Seleccionar',
		'm_tagmsg':'<p class="MoB-span"> Si deseas saber más sobre las etiquetas ve a <a class="MoB-span" href="http://mob.ciens.ucv.ve/tagsinfo" target="_blank"> TAGS </a> </p>',
		'm_msgcat':'Escoge una categoría',
		'm_error1':'Ya estas corriendo la herramienta de segmentación',
		'm_msgtinyb':'Todos los bloques pequeños dentro del nuevo desaparecerán, desea continuar?',
		'm_seltag':'Select the block\'s tag',
		'm_error2':'Necesita cubrir una mayor área de la página con bloques, presione el botón con la \'I\' para mayor información.',
		'm_error3':'Todavía queda uno o más errores que debe arreglar antes de enviar la segmentación, presione el botón con la \'I\' para mayor información.',
		'm_warn1':'Tu segmentación será enviada con una o más advertencias, desea continuar?',
		'm_selcol':'Selecciona la colección donde deseas guardar la página Web.',
		'm_editgran':'Inserta una granularidad de 0 a 10',
		'm_error4':'Ha ocurrido un error mientras se enviaban los datos, por favor intente de nuevo.',
		'm_error5':'Ha ocurrido un error al cargar la herramienta, por favor cierre esta ventana e intente de nuevo.',
		'm_overlap':'Existe una intersección entre dos o más bloques, puede usar la acción Cortar para resolver esto.',
		'al_error':'Error: ',
		'al_warning':'Alerta: ',
		'al_b': 'El bloque: ',
		'al_overlap1': ' y el bloque ',
		'al_overlap2': ' se  están intersectando.',
		'al_tag':' no tiene una etiqueta aún.',
		'al_gran1':' no cumple con la granularidad esperada (',
		'al_gran2':'), tiene una granularidad de: ',
		'al_gran3':' y un área de: ',
		'al_gran4':'mm2. Se espera un área mínima de: ',
		'al_gran5':'mm2, y un área máxima de: ',
		'bi_title':'Información del Bloque',
		'bi_area':'Área:',
		'bi_pos':'Posición:',
		'bi_w':'Ancho:',
		'bi_h':'Alto:',
		'bi_t':'Etiqueta:',
		'bi_g':'Granularidad:'
	},
	'en':{
		'a_info':'Information',
		'a_insert':'Insert new block',
		'a_delete':'Delete block',
		'a_merge':'Merge Blocks',
		'a_cut':'Cut blocks',
		'a_tag':'Edit block\'s tag ',
		'a_select':'Select block',
		'a_submit':'Submit segmentation',
		'i_legend': ' <b class="MoB-span"> Legend </b> </br><span style="color:rgb(90, 194, 236);" class="MoB-span"> <b class="MoB-span"> Accepted </b> </span> = The block is good. </br><span style="color:rgb(255, 193, 7); " class="MoB-span"> <b class="MoB-span"> Warning </b> </span> = The block\'s granularity it\'s too high above the set one. </br><span style="color:rgb(169, 68, 66);" class="MoB-span"> <b class="MoB-span"> Error </b> </span> = The block\'s granularity is not allowed, the block it\'s overlapping with another block, the block it\'s missing the tag.',
		'i_nblock':'#Blocks: ',
		'i_blockta':'Blocks total area: ',
		'i_gran':'Granularity: ',
		'i_editg':'edit',
		'i_div':'Divided in: ',
		'i_div2':' pieces',
		'i_blockma':'Min area for blocks: ',
		'i_totalma':'Total min area: ',
		'm_message':'MoB Message',
		'm_cancel':'Cancel',
		'm_select':'Select',
		'm_tagmsg':'<p class="MoB-span"> If you wanna know more about these tags go to <a class="MoB-span" href="http://mob.ciens.ucv.ve/tagsinfo" target="_blank"> TAGS</a> </p>',
		'm_msgcat':'choose the category',
		'm_error1':'you are already running the segmentation tool',
		'm_msgtinyb':'All the tiny blocks inside the new one will dissappear, want to continue?.',
		'm_seltag':'Select the block\'s tag',
		'm_error2':'You need to cover more space of the page with blocks, please click the \'I\' button for more info.',
		'm_error3':'There\'s still one or more errors you should fix before sending the segmentation, please click the \'I\' button for more info.',
		'm_warn1':'Your segmentation will be sent with one or more warnings. Want to continue?',
		'm_selcol':'Select the collection on which your segmentation will be saved',
		'm_editgran':'Insert the new granularity from 0 to 10',
		'm_error4':'There has been an error while sending the data, please try again.',
		'm_error5':'there has been an error trying to load the tool, please close this window and try again',
		'm_overlap':'There\'s an overlap between two or more blocks, you can use the Cut tool to solve this',
		'al_error':'Error: ',
		'al_warning':'Warning: ',
		'al_b': 'The block: ',
		'al_overlap1': ' and the block ',
		'al_overlap2': ' are overlapping with eachother.',
		'al_tag':' does not have a tag yet.',
		'al_gran1':' does not reach the expected granularity (',
		'al_gran2':'), it has a granularity of: ',
		'al_gran3':' and an area of: ',
		'al_gran4':'mm2. Expected a min area of: ',
		'al_gran5':'mm2, and a max area of: ',
		'bi_title':'Block\'s  Info',
		'bi_area':'Area:',
		'bi_pos':'Position:',
		'bi_w':'Width:',
		'bi_h':'Height:',
		'bi_t':'Tag:',
		'bi_g':'Granularity:'
	},
	'fr':{
		'a_info':'Information',
		'a_insert':'Insérer un nouveau bloc',
		'a_delete':'Supprimer le bloc',
		'a_merge':'Rejoignez les blocs',
		'a_cut':'Cortar bloques',
		'a_tag':'Couper des blocs',
		'a_select':'Sélectionnez un bloc',
		'a_submit':'Soumettre la segmentation',
		'i_legend': ' <b class="MoB-span"> Légende </b> </br><span style="color:rgb(90, 194, 236);" class="MoB-span"> <b class="MoB-span"> Acceptable </b> </span> = Le bloc est bien. </br><span style="color:rgb(255, 193, 7); " class="MoB-span"> <b class="MoB-span"> Alerte </b> </span> = La granularité du bloc est bien supérieure à celle choisie. </br><span style="color:rgb(169, 68, 66);" class="MoB-span"> <b class="MoB-span"> Erreur </b> </span> = La granularité du bloc n\'est pas acceptée, le bloc est en intersection avec un autre ou l\'étiquette est manquante.',
		'i_nblock':'#Blocs: ',
		'i_blockta':'Surface totale du bloc: ',
		'i_gran':'Granularité: ',
		'i_editg':'modifier',
		'i_div':'Divisé en: ',
		'i_div2':' parties',
		'i_blockma':'Surface minimale pour les blocs: ',
		'i_totalma':'Surface minimale totale: ',
		'm_message':'Message MoB',
		'm_cancel':'Annuler',
		'm_select':'Sélectionnez',
		'm_tagmsg':'<p class="MoB-span"> Si vous voulez en savoir plus sur les étiquettes, allez à <a class="MoB-span" href="http://mob.ciens.ucv.ve/tagsinfo" target="_blank"> TAGS </a> </p>',
		'm_msgcat':'Choisissez une catégorie',
		'm_error1':'Vous utilisez déjà l\'outil de ciblage',
		'm_msgtinyb':'Tous les petits blocs dans le nouveau disparaîtront, voulez-vous continuer?',
		'm_seltag':'Sélectionnez le tag du bloc',
		'm_error2':'Vous devez couvrir une plus grande zone de la page avec des blocs, appuyez sur le bouton avec le «I» pour plus d\'informations.',
		'm_error3':'Il y a encore une ou plusieurs erreurs qui doivent être corrigées avant d\'envoyer la segmentation, appuyez sur le bouton avec le «I» pour plus d\'informations.',
		'm_warn1':'Votre segmentation sera envoyée avec un ou plusieurs avertissements, voulez-vous continuer?',
		'm_selcol':'Sélectionnez la collection dans laquelle vous souhaitez enregistrer la page Web.',
		'm_editgran':'Insérer une granularité de 0 à 10',
		'm_error4':'Une erreur s\'est produite lors de l\'envoi des données. Veuillez réessayer.',
		'm_error5':'Une erreur s\'est produite lors du chargement de l\'outil, fermez cette fenêtre et réessayez.',
		'm_overlap':'Il existe une intersection entre deux ou plusieurs blocs, vous pouvez utiliser l\'action Couper pour résoudre ce problème.',
		'al_error':'Erreur: ',
		'al_warning':'Alerte: ',
		'al_b': 'Le bloc: ',
		'al_overlap1': ' et le bloc ',
		'al_overlap2': ' ils se croisent.',
		'al_tag':' Il n\'a pas encore d\'étiquette.',
		'al_gran1':' ne répond pas à la granularité attendue (',
		'al_gran2':'), Il a une granularité de: ',
		'al_gran3':' et une zone de: ',
		'al_gran4':'mm2. Une superficie minimale de: ',
		'al_gran5':'mm2, et une superficie maximale de: ',
		'bi_title':'Bloquer l\'information',
		'bi_area':'Zone:',
		'bi_pos':'Position:',
		'bi_w':'Largeur:',
		'bi_h':'Haut:',
		'bi_t':'Tag:',
		'bi_g':'Granularidad:'
	}

};